### PR TITLE
Prepare 0.1.3.1 release

### PR DESCRIPTION
**Pull request by brianjosephmckeon**

### CODE REVIEW

**Comment by brianjosephmckeon** [comment]
@andrewthad The laws test suite is failing. No rush on fixing this.

**Comment by andrewthad** [comment]
I've fixed all the Ord instances. It's strange that this had not been detected before now. It's uncommon to use the `Ord` instance for a Maybe-like type, so I doubt it was encountered by any applications. Anyway, good to have it fixed now.

**Comment by chessai** [comment]
> I've fixed all the Ord instances. It's strange that this had not been detected before now. It's uncommon to use the `Ord` instance for a Maybe-like type, so I doubt it was encountered by any applications. Anyway, good to have it fixed now.

pretty crazy. i remember copying these from the much older version of this library.

glad it's fixed now! i should have added these tests before.

**Comment by andrewthad** [comment]
What's strange is that the test for the Ord laws were already there. Either no one had ever noticed that the test suite was failing, or maybe something in quickcheck-classes or QuickCheck changed that caused this to start getting detected. I'll chalk it up to one of history's mysteries.

**Pull request merged**
